name: universal_io
version: 2.1.0
description: Cross-platform 'dart:io' that works in all platforms (browsers, Flutter, and VM).
homepage: https://github.com/dart-io-packages/universal_io
false_secrets:
  - /test/localhost.key

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  async: ^2.5.0
  lints: ^2.0.1
  stream_channel: ^2.1.0
  test: ^1.16.0