name: universal_io
version: 2.2.2
description: Cross-platform 'dart:io' that adds browser support for HttpClient and some other
  "dart:io" APIs.
homepage: https://github.com/dart-io-packages/universal_io
false_secrets:
  - /test/localhost.key

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.9.0
  typed_data: ^1.3.0

dev_dependencies:
  async: ^2.11.0
  lints: ^2.1.0
  stream_channel: ^2.1.1
  test: ^1.24.0