name: universal_io
version: 2.2.0
description: Cross-platform 'dart:io' that adds browser support for HttpClient and some other
  "dart:io" APIs.
homepage: https://github.com/dart-io-packages/universal_io
false_secrets:
  - /test/localhost.key

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  async: ^2.10.0
  lints: ^2.0.1
  stream_channel: ^2.1.1
  test: ^1.23.1