name: flutter_example
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io:
    path: '../'

dev_dependencies:
  flutter_test:
    sdk: flutter